openapi: 3.1.0
info:
  version: 1.0.0
  title: staging-api.tizo.co
  termsOfService: https://example.com/terms/
  contact:
    email: rcastano@tizo.app
    url: https://www.linkedin.com/company/tizo/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://tizo-dev.s3.us-east-1.amazonaws.com/logos/logo.png
  description: "# Introducción\r\n\r\n\r\nEsta api contiene todas las funcionalidades de envíos que usted necesita para integrarla en su negocio, en caso de que usted no tenga un sistema existente, le recomendamos que use las apps pronto disponibles en Play Store, Apple Store. Entre las principales funcionalidades se encuentran:\r\n\r\n\r\n- Creación de envíos usando los distintos aliados de Tizo.\r\n- Seguimiento en tiempo real, así como el historial de los envíos realizados.\r\n- Métricas de su negocio, así como algunas variables de su interés.\r\n- Zonas de cobertura disponibles, su \"libreta de contactos\", y direcciones predefinidas.\r\n\r\n# Comúniquese con nosotros\r\n\r\n- Correos: En para el equipo de tizo info@tizo.app  y a axel.garcia@tizo.app en caso de algún inconveniente con la API.\r\n- Síguenos en las siguientes plataformas para estar al tanto de las últimas mejoras y novedades: [Facebook](https://www.facebook.com/Tizo.appCA/), [Twitter](https://twitter.com/AppTizo), [Instagram](https://www.instagram.com/tizoapp/).\r\n\r\n\r\n [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/19319757-13ea3bc8-bfe2-4ffd-87ee-f2d3bb439c62?action=collection%2Ffork&collection-url=entityId%3D19319757-13ea3bc8-bfe2-4ffd-87ee-f2d3bb439c62%26entityType%3Dcollection%26workspaceId%3D957b370e-bb6a-4235-b1a9-43894e2c51eb#?env%5BTizo%20Vendors%5D=W3sia2V5IjoiYmFzZV91cmwiLCJ2YWx1ZSI6Imh0dHBzOi8vYXBpLnRpem8uY28iLCJlbmFibGVkIjp0cnVlLCJ0eXBlIjoiZGVmYXVsdCJ9LHsia2V5IjoiYXV0aF90b2tlbiIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6ImRlZmF1bHQifSx7ImtleSI6ImVudmlyb25tZW50IiwidmFsdWUiOiJkZXYiLCJlbmFibGVkIjp0cnVlLCJ0eXBlIjoiZGVmYXVsdCJ9LHsia2V5IjoibGFuZ3VhZ2UiLCJ2YWx1ZSI6ImVzIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6ImRlZmF1bHQifV0=)"
tags:
  - name: Aclaraciones importantes
    description: "## Autenticación.\r\n\r\nUna vez logueado, tus credenciales tienen acceso durante 7 días en nuestra plataforma, por lo que debes refrescar el token una vez ya expirado.\r\n\r\n## Headers\r\n\r\nPara un mejor uso de nuestra API, debes de tomar en cuenta que cada request que se haga, se recibe los siguientes headers.\r\n\r\n| Clave  | Valor |\r\n|-------|-------|\r\n| Authorization | Token | \r\n| Content-Type | application/json |\r\n| environment | ni, dev |\r\n| Accept-Language | es, en |"
servers:
  - url: https://staging-api.tizo.co/api/v1
paths:
  /auth/login:
    post:
      tags:
        - Login
      summary: Inicio de sesión
      description: null
      operationId: login
      security:
        - basic_auth:
            - Authorization
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Unauthorized
      requestBody:
        headers:
          environment:
            description: País donde se encuentra el usuario.
            schema:
              type: string
              example: ni
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        description: Echo payload
        required: true
      x-codeSamples:
        - lang: C#
          source: "var client = new RestClient(\"https://staging-api.tizo.co/api/v1/auth/login/\");\r\nclient.Timeout = -1;\r\nvar request = new RestRequest(Method.POST);\r\nrequest.AddHeader(\"Content-Type\", \"application/json\");\r\nvar body = @\"{\"\"username\"\": \"\"store_0\"\",\"\"password\"\": \"\"12\"\",\"\"typeUser\"\": \"\"store_api\"\"}\";\r\nrequest.AddParameter(\"application/json\", body,  ParameterType.RequestBody);\r\nIRestResponse response = client.Execute(request);\r\nConsole.WriteLine(response.Content);"
        - lang: PHP
          source: "<?php\r\n$client = new Client();\r\n$headers = [\r\n  'Authorization' => 'eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoic3RvcmVfYXBpIiwidXNlcm5hbWUiOiJzdG9yZV8wIiwiaWF0IjoxNjU1Nzk3NjQ5LCJleHAiOjE2NTY0MDI0NDl9.s-1eTUqzDnmCW98yN4CkFUNjkj_eCzjBe8qUHmO3GUcR35z-4i8o3MGzzEj-JztUcfewI1Sfm18HfPDA3IUR_Q',\r\n  'Content-Type' => 'application/json'\r\n];\r\n$body = '{\r\n  \"username\": \"store_0\",\r\n  \"password\": \"12\",\r\n  \"typeUser\": \"store_api\"\r\n}';\r\n$request = new Request('POST', 'https://staging-api.tizo.co/api/v1/auth/login/', $headers, $body);\r\n$res = $client->sendAsync($request)->wait();\r\necho $res->getBody();\r\n"
        - lang: Python
          source: "import requests\r\nimport json\r\n\r\nurl = \"https://staging-api.tizo.co/api/v1/auth/login/\"\r\n\r\npayload = json.dumps({\r\n  \"username\": \"store_0\",\r\n  \"password\": \"12\",\r\n  \"typeUser\": \"store_api\"\r\n})\r\nheaders = {\r\n  'Content-Type': 'application/json'\r\n}\r\n\r\nresponse = requests.request(\"POST\", url, headers=headers, data=payload)\r\n\r\nprint(response.text)\r\n"
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://staging-api.tizo.co/api/v1/auth/login
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Login:
      type: object
      properties:
        username:
          description: Nombre de usuario
          type: string
          required: true
          example: store_12
        password:
          description: Contraseña
          type: string
          required: true
          example: contraseña
        typeUser:
          description: Tipo de usuario (vendor, store_api)
          type: string
          required: true
          example: vendor
    Email:
      description: User email address
      type: string
      format: test
      example: john.smith@example.com
    User:
      type: object
      properties:
        username:
          description: User supplied username
          type: string
          minLength: 4
          example: John78
        firstName:
          description: User first name
          type: string
          minLength: 1
          example: John
        lastName:
          description: User last name
          type: string
          minLength: 1
          example: Smith
        email:
          $ref: '#/components/schemas/Email'
    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/User'
            type_user:
              type: string
              description: Tipo de usuario (vendor, store_api)
              example: vendor
            auth_token:
              type: string
              description: Token de autenticación
              example: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        message:
          type: string
          description: Mensaje de respuesta
          example: Hello
        status:
          type: integer
          description: Estado de la respuesta
          example: 200
