openapi: 3.1.0
info:
  version: 1.0.0
  title: api.tizo.co
  termsOfService: 'https://example.com/terms/'
  contact:
    email: rcastano@tizo.app
    url: 'https://www.linkedin.com/company/tizo/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://tizo-dev.s3.us-east-1.amazonaws.com/logos/logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Aclaraciones importantes
    description: 
      $ref: ./info-authentication.md
servers:
  - url: 'https://api.tizo.co/api/v1'
paths:
  /auth/reset-password:
    $ref: paths/auth/reset-password.yaml
  /auth/login:
    $ref: paths/auth/login.yaml
  /auth/permissions:
    $ref: paths/auth/permissions.yaml
  /auth/recovery-password:
    $ref: paths/auth/recovery-password.yaml
  /auth/refresh-token:
    $ref: paths/auth/refresh-token.yaml
  
  
  /delivery:
      $ref: paths/delivery/delivery.yaml
  /delivery/estimate:
      $ref: paths/delivery/estimate.yaml
  /delivery/new:
      $ref: paths/delivery/new.yaml
  /delivery/confirm/{code}/:
      $ref: paths/delivery/confirm.yaml
  
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.tizo.co/api/v1/auth/login'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: Authorization